name: Markdown content update
on:
  push:
    branches:
      - main
jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.REPO_PAT }}" \
          https://api.github.com/repos/${{ vars.REPO_OWNER }}/${{ vars.REPO_NAME }}/dispatches \
          -d '{"event_type":"TRIGGER_BUILD"}'
