name: Markdown content update
on:
  push:
    branches:
      - main
jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.REPO_PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ vars.REPO_OWNER }}/${{ vars.REPO_NAME }}/dispatches \
          -d "{\"event_type\": \"TRIGGER_BUILD"}"
