name: Markdown content update
on:
  push:
    branches:
      - main
jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: ${{ secrets.REPO_PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/semaeopus/semaeopus-wikisite-host/dispatches \
          -d '{"event": "TRIGGER_BUILD"}'
        shell: bash
